- name: Issuance certificate (nginx)
  shell: certbot {{obtain}} --nginx -d {{domains | join(',')}} --email {{email}} --non-interactive --agree-tos
  when: expiry == "nginx"

- name: Issuance certificate (webroot)
  shell: certbot {{obtain}} --webroot {{webroot_dir}} -d {{domains | join(',')}} --email {{email}} --non-interactive --agree-tos
  when: expiry == "webroot"

- name: Issuance certificate (apache)
  shell: certbot {{obtain}} --apache -d {{domains | join(',')}} --email {{email}} --non-interactive --agree-tos
  when: expiry == "apache" 

- name: Issuance certificate (standalone)
  shell: certbot {{obtain}} --standalone -d {{domains | join(',')}} --email {{email}} --non-interactive --agree-tos
  when: expiry == "standalone"

- name: Issuance certificate (manual)
  shell: certbot {{obtain}} --manual -d {{domains | join(',')}} --email {{email}} --non-interactive --agree-tos
  when: expiry == "manual"





   